[package]
name = "hyper/development-server"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Option = "sleitnick/option@1.0.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.0"
Comm = "sleitnick/comm@1.0.0"
Knit = "sleitnick/knit@1.7.0"



[server-dependencies]
profilestore = "lm-loleris/profilestore@1.0.3"